name: Pulumi

on:
  push:
    branches:
      - main

env:
  STACK_NAME: amplify
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --cwd pulumi
      - name: Test
        run: echo $STACK_NAME
      - name: Create Stack
        run: pulumi stack init $STACK_NAME
      - name: Update Stack
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: $STACK_NAME
          work-dir: pulumi
