name: Pulumi

on:
  push:
    branches:
      - main

env:
  PULUMI_DIRECTORY: pulumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  STACK_NAME: fullstack

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Install Brew
        run: |
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Install Cargo Lambda
        run: |
          brew tap cargo-lambda/cargo-lambda
          brew install cargo-lambda
      - name: Build
        run: cargo build --release --locked --manifest-path axum/Cargo.toml
  Pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    needs:
      - backend
    steps:
      - name: Set Variables
        run: echo "PULUMI_GLOBALS=--non-interactive --color always --emoji --stack $STACK_NAME --cwd $PULUMI_DIRECTORY" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Package Restore
        run: bun install --frozen-lockfile --cwd $PULUMI_DIRECTORY
      # - name: Create Stack
      #   run: pulumi stack init $PULUMI_GLOBALS 2> /dev/null
      # - name: Update Stack
      #   run: pulumi up --yes --skip-preview --suppress-outputs $PULUMI_GLOBALS
