name: Pulumi

on:
  push:
    branches:
      - main

env:
  PULUMI_DIRECTORY: pulumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  STACK_NAME: fullstack

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: mlugg/setup-zig@v1
      - uses: zerj9/setup-cargo-lambda@v0.1.1
      - name: Build
        run: cargo lambda build --arm64 --release --locked --manifest-path axum/Cargo.toml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: axum/target/lambda/axum/bootstrap
          retention-days: 5
  Pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    needs:
      - backend
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Set Variables
        run: echo "PULUMI_GLOBALS=--non-interactive --color always --emoji --stack $STACK_NAME --cwd $PULUMI_DIRECTORY" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Package Restore
        run: bun install --frozen-lockfile --cwd $PULUMI_DIRECTORY
      - name: Update Stack
        run: |
          # pulumi stack init $PULUMI_GLOBALS 2> /dev/null
          pulumi up --yes --skip-preview --suppress-outputs $PULUMI_GLOBALS
