name: Pulumi Update

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  PULUMI_DIRECTORY: pulumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  STACK_NAME: fullstack

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Zig
        uses: mlugg/setup-zig@v1
      - name: Install Cargo Lambda
        uses: zerj9/setup-cargo-lambda@v0.1.1
      - name: Build Lambda
        run: cargo lambda build --arm64 --release --locked --manifest-path backend/Cargo.toml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/target/lambda/axum/bootstrap
          retention-days: 1

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Package Restore
        run: (cd frontend && bun install --frozen-lockfile)
      - name: Build Website
        run: (cd frontend && bunx --bun vite build)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist/
          retention-days: 1

  pulumi:
    name: Pulumi Update
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: pulumi
      - name: Zip Lambda
        run: (cd pulumi/backend && zip bootstrap.zip bootstrap)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Package Restore
        run: bun install --frozen-lockfile --cwd $PULUMI_DIRECTORY
      - name: Update Stack
        run: |
          pulumiGlobal="--non-interactive --color always --emoji --stack $STACK_NAME --cwd $PULUMI_DIRECTORY"
          pulumi stack init $pulumiGlobal || true
          pulumi up --yes --skip-preview $pulumiGlobal
