name: Pulumi

on:
  push:
    branches:
      - main

env:
  PULUMI_DIRECTORY: pulumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo 'PULUMI_GLOBALS="--color always --emoji --non-interactive --stack amplify --cwd ${{ env.PULUMI_DIRECTORY }}"' >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Package Restore
        run: bun install --cwd $PULUMI_DIRECTORY
      # - name: Create Stack
      #   run: pulumi stack init $PULUMI_GLOBALS 2> /dev/null
      - name: Update Stack
        run: pulumi up --yes --skip-preview --suppress-outputs $PULUMI_GLOBALS
