name: Pulumi

on:
  push:
    branches:
      - main

env:
  STACK_NAME: amplify
  PULUMI_DIRECTORY: pulumi
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_GLOBALS: ${{ format('--color always --emoji --non-interactive --stack {} --cwd {}', env.STACK_NAME, env.PULUMI_DIRECTORY) }}

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --cwd pulumi
      # - name: Create Stack
      #   run: pulumi stack init $PULUMI_GLOBALS 2> /dev/null
      - name: Update Stack
        run: pulumi up $PULUMI_GLOBALS
